# Generated by Django 4.2.7 on 2025-10-02 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ending_id",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "ending_type",
                    models.CharField(
                        choices=[
                            ("victory", "Victory"),
                            ("defeat", "Defeat"),
                            ("betrayal", "Betrayal"),
                            ("comedy", "Comedy"),
                            ("secret", "Secret"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(max_length=10)),
                ("achievement_text", models.CharField(max_length=200)),
                ("is_secret", models.BooleanField(default=False)),
                ("requirements", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scene_id",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("ascii_art", models.TextField(blank=True)),
                ("is_ending", models.BooleanField(default=False)),
                ("is_death", models.BooleanField(default=False)),
                (
                    "scene_type",
                    models.CharField(
                        choices=[
                            ("story", "Story Scene"),
                            ("death", "Death Scene"),
                            ("ending", "Ending Scene"),
                            ("hub", "Hub Scene"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["scene_id"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("is_critical", models.BooleanField(default=False)),
                ("is_consumable", models.BooleanField(default=False)),
                ("is_trap", models.BooleanField(default=False)),
                ("icon", models.CharField(default="📦", max_length=10)),
                (
                    "found_in_scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_here",
                        to="castle_adventure.scene",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("inventory", models.JSONField(default=list)),
                ("visited_scenes", models.JSONField(default=list)),
                ("flags", models.JSONField(default=dict)),
                ("game_started", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "ending_reached",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("choices_made", models.IntegerField(default=0)),
                ("deaths", models.IntegerField(default=0)),
                ("items_collected", models.IntegerField(default=0)),
                (
                    "current_scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_games",
                        to="castle_adventure.scene",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EndingUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ending",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="castle_adventure.ending",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("session_key", "ending"), ("user", "ending")},
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("choice_letter", models.CharField(max_length=1)),
                ("order", models.IntegerField(default=0)),
                (
                    "from_scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices_from",
                        to="castle_adventure.scene",
                    ),
                ),
                (
                    "requires_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="castle_adventure.item",
                    ),
                ),
                (
                    "to_scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices_to",
                        to="castle_adventure.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("from_scene", "choice_letter")},
            },
        ),
    ]
